### ISSUE TITLE
build fails under ghc 7.10.1

### ISSUE THREAD

**Issue by nponeccop** [feuerbach/bert#13]
A problem with overlapped instances in `Parser.hs`

**Comment by feuerbach** [comment]
6.10 is *very* old. Why is this important?

**Comment by nponeccop** [comment]
It's `7.10.1`, my bad.

**Comment by feuerbach** [comment]
Ok, thanks for reporting. Fixed in 1.2.2.4.

**Comment by 5HT** [comment]
Thanks!
